# 1.Import Libraries

In [2]:
from vnstock import *
import pandas as pd

# 2.Stock analysis

In [3]:
stock_ls_analysis("ACB, HDB, MBB, GMD, VIX")

Mã CP                            ACB    GMD    HDB     MBB    VIX
Vốn hóa (tỷ)                  108753  25367  70775  130327  13054
Giá                            28000  81700  24300   24650  19500
Số phiên tăng/giảm liên tiếp       2      4      2       1      1
P/E                              6.8   11.4    7.0     6.3   13.5
PEG                              0.4    0.1    0.2     0.3    0.1
P/B                              1.5    3.0    1.5     1.3    1.5
Cổ tức                           0.0    0.0    0.0     0.0    0.0
ROE                            0.248  0.287  0.247   0.245  0.116
ROA                            0.024  0.166   0.02   0.025  0.112
Nợ/Vốn CSH                       9.1    0.2   12.0     8.8    0.0
LNST 5 năm                     0.256   0.04  0.288   0.276  0.349
Doanh thu 5 năm                0.185  0.073  0.228   0.193  0.291
LNST quý gần nhất             -0.008 -0.548  0.348  -0.136  -0.04
Doanh thu quý gần nhất        -0.005  0.036  0.357  -0.026  0.056
LNST năm tới                    0.09  1.288  0.185   0.122  0.016
Doanh thu năm tới              0.081    0.0  0.144   0.248    0.4
RSI                             56.1   64.4   63.7    56.0   48.3
RS                              70.0   79.0   74.0    81.0   60.0

In [4]:
industry_analysis("ACB", lang="vi")

Mã CP,ACB,VCB,BID,CTG,TCB,VPB,MBB,HDB,VIB,SSB,STB,LPB,SHB,TPB,EIB,OCB,MSB,NAB,BAB,ABB
Vốn hóa (tỷ),108753,528728,304403,192783,166967,156298,130327,70775,59869,56403,54860,50001,41385,41171,31597,30514,29300,16929,11289,8330
Giá,28000,94600,53400,35900,47400,19700,24650,24300,23600,22600,29100,19550,11300,18700,18150,14850,14650,16000,12600,8048
Số phiên tăng/giảm liên tiếp,2,1,2,2,1,1,1,2,1,3,1,1,1,1,0,1,1,1,1,-1
P/E,6.8,16.0,14.1,9.6,9.3,15.5,6.3,7.0,7.0,15.3,7.1,9.0,5.5,9.2,14.6,7.3,6.3,6.5,13.5,18.4
PEG,0.4,1.5,0.7,0.5,-0.9,-0.3,0.3,0.2,6.3,-1.7,0.1,0.4,-1.8,-0.3,-0.6,0.4,10.4,0.1,-4.7,-0.3
P/B,1.5,3.1,2.5,1.5,1.3,1.1,1.3,1.5,1.6,1.9,1.2,1.5,0.8,1.3,1.4,1.0,0.9,1.1,1.0,0.6
Cổ tức,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.053,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ROE,0.248,0.216,0.198,0.171,0.148,0.087,0.245,0.247,0.243,0.13,0.183,0.192,0.161,0.137,0.101,0.153,0.16,0.188,0.081,0.034
ROA,0.024,0.018,0.01,0.01,0.023,0.014,0.025,0.02,0.023,0.015,0.012,0.016,0.013,0.013,0.011,0.019,0.019,0.014,0.006,0.003
interestMargin,0.039,0.03,0.026,0.029,0.04,0.056,0.048,0.048,0.047,0.03,0.037,0.032,0.036,0.039,0.025,0.036,0.041,0.035,0.018,0.021
Tỉ lệ nợ xấu,0.012,0.01,0.013,0.011,0.012,0.05,0.016,0.018,0.031,0.019,0.023,0.013,0.028,0.02,0.027,0.028,0.029,0.021,0.009,0.029
Nợ/Vốn CSH,9.1,9.9,17.7,14.9,5.5,4.8,8.8,12.0,9.8,7.8,13.7,10.2,11.6,9.9,8.0,7.1,7.5,12.8,13.0,11.0
LNST 5 năm,0.256,0.177,0.242,0.304,0.163,0.063,0.276,0.288,0.313,0.494,0.339,0.422,0.344,0.198,0.268,0.134,0.398,0.347,0.048,-0.087
Doanh thu 5 năm,0.185,0.115,0.105,0.199,0.169,0.099,0.193,0.228,0.295,0.274,0.175,0.262,0.259,0.236,0.08,0.122,0.211,0.336,0.088,0.083
LNST quý gần nhất,-0.008,0.287,0.325,0.584,-0.038,-0.163,-0.136,0.348,-0.114,0.279,0.382,1.647,-0.719,-0.609,2.327,-0.033,-0.635,1.382,5.116,NaN
Doanh thu quý gần nhất,-0.005,0.012,0.152,0.062,0.057,0.185,-0.026,0.357,-0.03,0.199,0.132,1.084,0.265,0.054,0.758,0.055,-0.142,1.0,1.219,0.124
LNST năm tới,0.09,0.116,0.145,0.137,-0.084,0.532,0.122,0.185,0.103,0.36,0.542,0.098,0.109,0.223,-0.09,0.562,0.212,0.089,0.107,0.912
Doanh thu năm tới,0.081,0.075,0.108,0.135,0.084,0.297,0.248,0.144,0.104,0.328,0.106,-0.054,0.156,0.105,0.117,0.215,0.185,0.133,0.071,0.163
RSI,56.1,51.0,58.3,59.2,65.0,59.4,56.0,63.7,56.9,61.6,37.6,71.3,46.7,50.6,48.7,52.8,51.0,46.1,54.8,48.5
rs,70.0,52.0,71.0,76.0,88.0,52.0,81.0,74.0,78.0,40.0,30.0,87.0,40.0,47.0,42.0,57.0,52.0,51.0,46.0,40.0

In [5]:
# Top 5 bank stocks with the highest Roe
data = {
    'Stock': ['ACB', 'VCB', 'BID', 'CTG', 'TCB', 'VPB', 'MBB', 'HDB', 'VIB', 'SSB', 'STB', 'LPB', 'SHB', 'TPB', 'EIB', 'OCB', 'MSB', 'NAB', 'BAB', 'ABB'],
    'Roe': [0.248, 0.216, 0.198, 0.171, 0.148, 0.087, 0.245, 0.247, 0.243, 0.13, 0.183, 0.192, 0.161, 0.137, 0.101, 0.153, 0.16, 0.188, 0.081, 0.034]
}
df = pd.DataFrame(data)

top_5 = df.sort_values(by='Roe', ascending=False).head(5)
top_5

  Stock    Roe
0   ACB  0.248
7   HDB  0.247
6   MBB  0.245
8   VIB  0.243
1   VCB  0.216

In [6]:
df1 = stock_evaluation (symbol='ACB', period=1, time_window='W')
df1.tail()

,ticker,fromDate,toDate,PE,PB,industryPE,vnindexPE,industryPB,vnindexPB
48,ACB,2024-03-11,2024-03-15,6.6,1.5,10.1,15.4,1.6,1.7
49,ACB,2024-03-18,2024-03-22,6.7,1.5,10.2,15.4,1.6,1.7
50,ACB,2024-03-25,2024-03-29,6.8,1.5,10.4,15.6,1.6,1.8
51,ACB,2024-04-01,2024-04-05,6.8,1.5,10.3,15.6,1.6,1.8
52,ACB,2024-04-08,2024-04-12,6.6,1.5,10.3,15.5,1.6,1.7

In [7]:
df2 = stock_evaluation(symbol='HDB', period=1, time_window='W')
df2.tail()

,ticker,fromDate,toDate,PE,PB,industryPE,vnindexPE,industryPB,vnindexPB
48,HDB,2024-03-11,2024-03-15,6.7,1.4,10.1,15.4,1.6,1.7
49,HDB,2024-03-18,2024-03-22,6.6,1.4,10.2,15.4,1.6,1.7
50,HDB,2024-03-25,2024-03-29,7.0,1.5,10.4,15.6,1.6,1.8
51,HDB,2024-04-01,2024-04-05,6.8,1.5,10.3,15.6,1.6,1.8
52,HDB,2024-04-08,2024-04-12,6.9,1.5,10.3,15.5,1.6,1.7

In [8]:
df3 = stock_evaluation (symbol='GMD', period=1, time_window='W')
df3.tail()

,ticker,fromDate,toDate,PE,PB,industryPE,vnindexPE,industryPB,vnindexPB
48,GMD,2024-03-11,2024-03-15,11.1,2.9,15.7,15.4,2.0,1.7
49,GMD,2024-03-18,2024-03-22,10.9,2.8,15.8,15.4,2.0,1.7
50,GMD,2024-03-25,2024-03-29,11.1,2.9,15.8,15.6,2.0,1.8
51,GMD,2024-04-01,2024-04-05,11.1,2.9,15.8,15.6,2.0,1.8
52,GMD,2024-04-08,2024-04-12,11.1,2.9,15.7,15.5,2.0,1.7

In [9]:
df4 = stock_evaluation (symbol='MBB', period=1, time_window='W')
df4.tail()

,ticker,fromDate,toDate,PE,PB,industryPE,vnindexPE,industryPB,vnindexPB
48,MBB,2024-03-11,2024-03-15,6.0,1.3,10.1,15.4,1.6,1.7
49,MBB,2024-03-18,2024-03-22,6.2,1.3,10.2,15.4,1.6,1.7
50,MBB,2024-03-25,2024-03-29,6.5,1.4,10.4,15.6,1.6,1.8
51,MBB,2024-04-01,2024-04-05,6.2,1.3,10.3,15.6,1.6,1.8
52,MBB,2024-04-08,2024-04-12,6.1,1.3,10.3,15.5,1.6,1.7

In [10]:
df5 = stock_evaluation (symbol='VIX', period=1, time_window='W')
df5.tail()

,ticker,fromDate,toDate,PE,PB,industryPE,vnindexPE,industryPB,vnindexPB
48,VIX,2024-03-11,2024-03-15,13.8,1.5,24.3,15.4,1.7,1.7
49,VIX,2024-03-18,2024-03-22,13.8,1.5,24.3,15.4,1.7,1.7
50,VIX,2024-03-25,2024-03-29,14.4,1.6,24.9,15.6,1.7,1.8
51,VIX,2024-04-01,2024-04-05,14.0,1.5,24.6,15.6,1.7,1.8
52,VIX,2024-04-08,2024-04-12,13.4,1.5,23.8,15.5,1.6,1.7